### ISSUE TITLE
Loss of flight controls in newly created save file. 

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#898]
This bug was introduced by #893 

When running a new campaign and immediately saving the game, the saved game now contains three values separated by a slash in the governors for the flight controls. 

The values are also quite low, so the flight controls are almost non-existent. 

For reference here is a save file created by the 0.8.x version of the game engine:
[Llama.begin.csv](https://github.com/user-attachments/files/17518408/Llama.begin.csv)

And here is a save file created after that pull request was merged:
[Llama.begin.csv](https://github.com/user-attachments/files/17518453/Llama.begin.csv)

**Comment by BenjamenMeyer** [comment]
Guessing this will apply to 0.9.x too

**Comment by royfalk** [comment]
Correction - #893 did not introduce this. It introduce the capability to serialize a resource int the format of:

_<current>  / <max_damaged> / <max>_

However, it did not introduce any code that uses it.

The actual bug is probably in #896 (@evertvorster please confirm). The Yaw_Governor_Left/Yaw_Governor_Right save a value of _0.01/0.01/0.01_. It shouldn't be too hard to figure out why.

**Comment by evertvorster** [comment]
This bug is fixed! Yay!

**Comment by royfalk** [comment]
Sorry. I fixed it but didn't link the PR to it.

**Comment by evertvorster** [comment]
Hmm, this bug was present in master before #986 was merged. I think Benjamin also noticed some loss of Yaw controls a while back, when loading a save file. 
However, it is fixed now.

**Comment by BenjamenMeyer** [comment]
Yes, I've noticed loss of yaw on and off. Usually occurred when launching. Not sure I've seen it in master in a while...but I don't get to play often right now. Will keep an eye out for it.

**Comment by stephengtuggy** [comment]
I am still seeing loss of yaw controls pretty consistently with the 0.9.x code. Is this bug supposed to be fixed there?

**Comment by stephengtuggy** [comment]
> I don't know. What was the cutoff point for 0.9?
> 
> There were actually two bugs related to loss of yaw control:
> 
> 1. The CSV got mangled in saving or loading, and yaw values, which came fairly last, were moved one right and read 0.
> 2. This issue which saved some drive values as current/damaged_max/max, which somehow missed a multiplier and saved really low values. Yaw was not 0 but close to it.
> 
> Take a look at your llama.csv and check the yaw values. That should tell you which bug it is.

In my very first savegame on this Windows box, the last four values in Llama.begin.csv are `45,45,45,V:\Assets-Production`. In the second and third savegames, the values are `45,0,0,V:\Assets-Production`. So this is the first issue, evidently.

**Comment by stephengtuggy** [comment]
> > I don't know. What was the cutoff point for 0.9?
> > There were actually two bugs related to loss of yaw control:
> > 
> > 1. The CSV got mangled in saving or loading, and yaw values, which came fairly last, were moved one right and read 0.
> > 2. This issue which saved some drive values as current/damaged_max/max, which somehow missed a multiplier and saved really low values. Yaw was not 0 but close to it.
> > 
> > Take a look at your llama.csv and check the yaw values. That should tell you which bug it is.
> 
> In my very first savegame on this Windows box, the last four values in Llama.begin.csv are `45,45,45,V:\Assets-Production`. In the second and third savegames, the values are `45,0,0,V:\Assets-Production`. So this is the first issue, evidently.

Filed a new ticket for this. #962
